name: Test Query 10
on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    # Use the postgis image to start a postgres service
    #
    # See the following links for more information:
    # https://hub.docker.com/_/postgis
    # https://docs.github.com/en/actions/guides/about-service-containers
    # https://docs.github.com/en/actions/guides/creating-postgresql-service-containers
    services:
      postgres:
        image: postgis/postgis
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install JS dependencies
      run: npm install
    - name: Install GDAL (for ogr2ogr)
      run: sudo apt install gdal-bin -y
    - name: Load test data
      run: __scripts__/load_data.sh
    - name: Enable PostGIS extension
      env:
        PGPASSWORD: ${{ secrets.532673 }}
      run: psql -U postgres -h localhost -p 5432 -d assignment01 -c 'CREATE EXTENSION IF NOT EXISTS postgis;'
    - name: Run tests
      run: |
        npm test __tests__/test_query10.js
